name: CI - MLIR-AIE-based Testing

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MLIR-AIE-Version: 0.0.1.2025071717+c5b3be6
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --extra dev

      - name: Cache MLIR-AIE setup
        id: cache-binary
        uses: actions/cache@v4
        with:
          path: mlir_aie
          key: mlir_aie-${{ env.MLIR-AIE-Version }}

      - name: Download and setup MLIR-AIE
        if: steps.cache-binary.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/Xilinx/mlir-aie/releases/download/latest-wheels-2/mlir_aie-${{ env.MLIR-AIE-Version }}-cp310-cp310-manylinux_2_35_x86_64.whl -O mlir_aie.whl
          unzip -q mlir_aie.whl
      - name: Add MLIR-AIE to PATH
        run: |
          echo "$(pwd)/mlir_aie/bin" >> $GITHUB_PATH
          echo "PATH after adding MLIR-AIE:"
          echo $PATH
      - name: Test aie-opt version
        run: |
          aie-opt --version

      - name: Run all tests
        run: uv run lit tests/filecheck -v
